// <auto-generated />
namespace MediaShop.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_confirmation_token : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_confirmation_token));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131000576_Add_confirmation_token"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
