//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaShop.WebApi.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaShop.WebApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        internal static string ClaimTypeId {
            get {
                return ResourceManager.GetString("ClaimTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission.
        /// </summary>
        internal static string ClaimTypePermission {
            get {
                return ResourceManager.GetString("ClaimTypePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product not found.
        /// </summary>
        internal static string ContentDownloadError {
            get {
                return ResourceManager.GetString("ContentDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content upload error..
        /// </summary>
        internal static string ContentUploadError {
            get {
                return ResourceManager.GetString("ContentUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An attempt to delete with a null identifier.
        /// </summary>
        internal static string DeleteWithNullId {
            get {
                return ResourceManager.GetString("DeleteWithNullId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorized data is empty.
        /// </summary>
        internal static string EmptyAutorizedData {
            get {
                return ResourceManager.GetString("EmptyAutorizedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty condition list.
        /// </summary>
        internal static string EmptyConditionList {
            get {
                return ResourceManager.GetString("EmptyConditionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data cannot be empty..
        /// </summary>
        internal static string EmptyRegisterDate {
            get {
                return ResourceManager.GetString("EmptyRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data cannot be empty.
        /// </summary>
        internal static string EmtyData {
            get {
                return ResourceManager.GetString("EmtyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You cannot download this product.
        /// </summary>
        internal static string ErrorDownload {
            get {
                return ResourceManager.GetString("ErrorDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error is occurred.
        /// </summary>
        internal static string ErrorFindService {
            get {
                return ResourceManager.GetString("ErrorFindService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An attempt to get with a null identifier.
        /// </summary>
        internal static string GetWithNullId {
            get {
                return ResourceManager.GetString("GetWithNullId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id can not be 0.
        /// </summary>
        internal static string IncorrectId {
            get {
                return ResourceManager.GetString("IncorrectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications for user with this id not found.
        /// </summary>
        internal static string NotFoundNotification {
            get {
                return ResourceManager.GetString("NotFoundNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not found product with this ID.
        /// </summary>
        internal static string NotFoundProduct {
            get {
                return ResourceManager.GetString("NotFoundProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notification is not valid.
        /// </summary>
        internal static string NotValidNotification {
            get {
                return ResourceManager.GetString("NotValidNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are not authorized.
        /// </summary>
        internal static string NullTokenData {
            get {
                return ResourceManager.GetString("NullTokenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product has unknow type.
        /// </summary>
        internal static string UnknowProductType {
            get {
                return ResourceManager.GetString("UnknowProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
