//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaShop.WebApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaShop.WebApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ClaimTypeId {
            get {
                return ResourceManager.GetString("ClaimTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string ClaimTypePermission {
            get {
                return ResourceManager.GetString("ClaimTypePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        internal static string ContentDownloadError {
            get {
                return ResourceManager.GetString("ContentDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content upload error..
        /// </summary>
        internal static string ContentUploadError {
            get {
                return ResourceManager.GetString("ContentUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to delete with a null identifier.
        /// </summary>
        internal static string DeleteWithNullId {
            get {
                return ResourceManager.GetString("DeleteWithNullId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized data is empty.
        /// </summary>
        internal static string EmptyAutorizedData {
            get {
                return ResourceManager.GetString("EmptyAutorizedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty condition list.
        /// </summary>
        internal static string EmptyConditionList {
            get {
                return ResourceManager.GetString("EmptyConditionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be empty..
        /// </summary>
        internal static string EmptyRegisterDate {
            get {
                return ResourceManager.GetString("EmptyRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be empty.
        /// </summary>
        internal static string EmtyData {
            get {
                return ResourceManager.GetString("EmtyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot download this product.
        /// </summary>
        internal static string ErrorDownload {
            get {
                return ResourceManager.GetString("ErrorDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error is occurred.
        /// </summary>
        internal static string ErrorFindService {
            get {
                return ResourceManager.GetString("ErrorFindService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to get with a null identifier.
        /// </summary>
        internal static string GetWithNullId {
            get {
                return ResourceManager.GetString("GetWithNullId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect inpute data.
        /// </summary>
        internal static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id can not be 0.
        /// </summary>
        internal static string IncorrectId {
            get {
                return ResourceManager.GetString("IncorrectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications for user with this id not found.
        /// </summary>
        internal static string NotFoundNotification {
            get {
                return ResourceManager.GetString("NotFoundNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found product with this ID.
        /// </summary>
        internal static string NotFoundProduct {
            get {
                return ResourceManager.GetString("NotFoundProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification is not valid.
        /// </summary>
        internal static string NotValidNotification {
            get {
                return ResourceManager.GetString("NotValidNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized.
        /// </summary>
        internal static string NullTokenData {
            get {
                return ResourceManager.GetString("NullTokenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has unknow type.
        /// </summary>
        internal static string UnknowProductType {
            get {
                return ResourceManager.GetString("UnknowProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
