//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaShop.BusinessLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaShop.BusinessLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is not add in cart.
        /// </summary>
        internal static string AddContentInCart {
            get {
                return ResourceManager.GetString("AddContentInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation deserialization is not successful.
        /// </summary>
        internal static string BadDeserializer {
            get {
                return ResourceManager.GetString("BadDeserializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media shop.
        /// </summary>
        internal static string DefaultNotificationTitle {
            get {
                return ResourceManager.GetString("DefaultNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is not delete from cart.
        /// </summary>
        internal static string DeleteContentFromCart {
            get {
                return ResourceManager.GetString("DeleteContentFromCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product error.
        /// </summary>
        internal static string DeleteProductError {
            get {
                return ResourceManager.GetString("DeleteProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to delete with a null identifier.
        /// </summary>
        internal static string DeleteWithNullId {
            get {
                return ResourceManager.GetString("DeleteWithNullId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting mime for an empty file.
        /// </summary>
        internal static string ErrorGettingMime {
            get {
                return ResourceManager.GetString("ErrorGettingMime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content already exist in cart.
        /// </summary>
        internal static string ExistContentInCart {
            get {
                return ResourceManager.GetString("ExistContentInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is not exist.
        /// </summary>
        internal static string ExistProductInDataBase {
            get {
                return ResourceManager.GetString("ExistProductInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving product by ID.
        /// </summary>
        internal static string GetProductError {
            get {
                return ResourceManager.GetString("GetProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to get with a null identifier.
        /// </summary>
        internal static string GetWithNullId {
            get {
                return ResourceManager.GetString("GetWithNullId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;image/gif&quot;,
        ///                &quot;image/jpeg&quot;,
        ///                &quot;image/pjpeg&quot;,
        ///                &quot;image/png&quot;,
        ///                &quot;image/x-png&quot;,
        ///                &quot;image/svg + xml&quot;,
        ///                &quot;image/tiff&quot;,
        ///                &quot;image/vnd.microsoft.icon&quot;,
        ///                &quot;image/vnd.wap.wbmp&quot;,
        ///                &quot;image/webp&quot;.
        /// </summary>
        internal static string imageType {
            get {
                return ResourceManager.GetString("imageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid content identificator.
        /// </summary>
        internal static string InvalidContentId {
            get {
                return ResourceManager.GetString("InvalidContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect id value.
        /// </summary>
        internal static string InvalidIdValue {
            get {
                return ResourceManager.GetString("InvalidIdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase transaction is not successfully.
        /// </summary>
        internal static string InvalidTransactionBuyContent {
            get {
                return ResourceManager.GetString("InvalidTransactionBuyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward seller transaction is not successfully.
        /// </summary>
        internal static string InvalidTransactionRewardSeller {
            get {
                return ResourceManager.GetString("InvalidTransactionRewardSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write down persentage for store is not successfully.
        /// </summary>
        internal static string InvalidTransactionWriteDownPersentageStore {
            get {
                return ResourceManager.GetString("InvalidTransactionWriteDownPersentageStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be less than or equal zerro.
        /// </summary>
        internal static string LessThanOrEqualToZeroValue {
            get {
                return ResourceManager.GetString("LessThanOrEqualToZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256.
        /// </summary>
        internal static string MAX_CONTENT {
            get {
                return ResourceManager.GetString("MAX_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.
        /// </summary>
        internal static string MaxHeightCompressedImage {
            get {
                return ResourceManager.GetString("MaxHeightCompressedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.
        /// </summary>
        internal static string MaxWidthCompressedImage {
            get {
                return ResourceManager.GetString("MaxWidthCompressedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noreply.mediashop@gmail.com.
        /// </summary>
        internal static string MediaShopMailAddress {
            get {
                return ResourceManager.GetString("MediaShopMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ayTYh?2-3xtUB26j.
        /// </summary>
        internal static string MediaShopMailPassword {
            get {
                return ResourceManager.GetString("MediaShopMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;audio/basic&quot;,
        ///                &quot;audio/L24&quot;,
        ///                &quot;audio/mp4&quot;,
        ///                &quot;audio/aac&quot;,
        ///                &quot;audio/mpeg&quot;,
        ///                &quot;audio/ogg&quot;,
        ///                &quot;audio/vorbis&quot;,
        ///                &quot;audio/x - ms - wma&quot;,
        ///                &quot;audio/x - ms - wax&quot;,
        ///                &quot;audio/vnd.rn - realaudio&quot;,
        ///                &quot;audio/vnd.wave&quot;,
        ///                &quot;audio/webm&quot;.
        /// </summary>
        internal static string musicType {
            get {
                return ResourceManager.GetString("musicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is not exist in Cart.
        /// </summary>
        internal static string NotExistContentInCart {
            get {
                return ResourceManager.GetString("NotExistContentInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has not been subscribed to receive notification.
        /// </summary>
        internal static string NotSubscribedUserMessage {
            get {
                return ResourceManager.GetString("NotSubscribedUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content can not be null.
        /// </summary>
        internal static string NullOrEmptyContent {
            get {
                return ResourceManager.GetString("NullOrEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be null.
        /// </summary>
        internal static string NullOrEmptyValue {
            get {
                return ResourceManager.GetString("NullOrEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String can not be null or empty.
        /// </summary>
        internal static string NullOrEmptyValueString {
            get {
                return ResourceManager.GetString("NullOrEmptyValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s registration message from Media shop. Follow the link to continue: {0}.
        /// </summary>
        internal static string RegisterUserMailBody {
            get {
                return ResourceManager.GetString("RegisterUserMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satate of Content is not valid.
        /// </summary>
        internal static string StateContentError {
            get {
                return ResourceManager.GetString("StateContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has unknow type.
        /// </summary>
        internal static string UnknowProductType {
            get {
                return ResourceManager.GetString("UnknowProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is not update in cart.
        /// </summary>
        internal static string UpdateContentInCart {
            get {
                return ResourceManager.GetString("UpdateContentInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update  product error.
        /// </summary>
        internal static string UpdateProductError {
            get {
                return ResourceManager.GetString("UpdateProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload product error.
        /// </summary>
        internal static string UploadProductError {
            get {
                return ResourceManager.GetString("UploadProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;video/mpeg&quot;,
        ///                &quot;video/mp4&quot;,
        ///                &quot;video/ogg&quot;,
        ///                &quot;video/quicktime&quot;,
        ///                &quot;video/webm&quot;,
        ///                &quot;video/x - ms - wmv&quot;,
        ///                &quot;video/x - flv&quot;,
        ///                &quot;video/3gpp&quot;,
        ///                &quot;video/3gpp2&quot;.
        /// </summary>
        internal static string videoType {
            get {
                return ResourceManager.GetString("videoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WaterMark {
            get {
                object obj = ResourceManager.GetObject("WaterMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5.
        /// </summary>
        internal static string WatermarkOpacity {
            get {
                return ResourceManager.GetString("WatermarkOpacity", resourceCulture);
            }
        }
    }
}
