//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaShop.BusinessLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaShop.BusinessLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content is not add in cart.
        /// </summary>
        internal static string AddContentInCart {
            get {
                return ResourceManager.GetString("AddContentInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment is not add in repository.
        /// </summary>
        internal static string BadAddPayment {
            get {
                return ResourceManager.GetString("BadAddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation deserialization is not successful.
        /// </summary>
        internal static string BadDeserializer {
            get {
                return ResourceManager.GetString("BadDeserializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count content in can not be null.
        /// </summary>
        internal static string CountContentInCartIsNull {
            get {
                return ResourceManager.GetString("CountContentInCartIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email not sent after {0} attempted.
        /// </summary>
        internal static string CountOfTryToEmailSendExceptionMessage {
            get {
                return ResourceManager.GetString("CountOfTryToEmailSendExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Media shop.
        /// </summary>
        internal static string DefaultNotificationTitle {
            get {
                return ResourceManager.GetString("DefaultNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content is not delete from cart.
        /// </summary>
        internal static string DeleteContentFromCart {
            get {
                return ResourceManager.GetString("DeleteContentFromCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete product error.
        /// </summary>
        internal static string DeleteProductError {
            get {
                return ResourceManager.GetString("DeleteProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An attempt to delete with a null identifier.
        /// </summary>
        internal static string DeleteWithNullId {
            get {
                return ResourceManager.GetString("DeleteWithNullId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error getting mime for an empty file.
        /// </summary>
        internal static string ErrorGettingMime {
            get {
                return ResourceManager.GetString("ErrorGettingMime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content already exist in cart.
        /// </summary>
        internal static string ExistContentInCart {
            get {
                return ResourceManager.GetString("ExistContentInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment already exist.
        /// </summary>
        internal static string ExistPayment {
            get {
                return ResourceManager.GetString("ExistPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product is not exist.
        /// </summary>
        internal static string ExistProductInDataBase {
            get {
                return ResourceManager.GetString("ExistProductInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation Payment was failed.
        /// </summary>
        internal static string FailedOperationPayment {
            get {
                return ResourceManager.GetString("FailedOperationPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error retrieving product by ID.
        /// </summary>
        internal static string GetProductError {
            get {
                return ResourceManager.GetString("GetProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An attempt to get with a null identifier.
        /// </summary>
        internal static string GetWithNullId {
            get {
                return ResourceManager.GetString("GetWithNullId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;image/gif&quot;,
        ///                &quot;image/jpeg&quot;,
        ///                &quot;image/pjpeg&quot;,
        ///                &quot;image/png&quot;,
        ///                &quot;image/x-png&quot;,
        ///                &quot;image/svg + xml&quot;,
        ///                &quot;image/tiff&quot;,
        ///                &quot;image/vnd.microsoft.icon&quot;,
        ///                &quot;image/vnd.wap.wbmp&quot;,
        ///                &quot;image/webp&quot;.
        /// </summary>
        internal static string imageType {
            get {
                return ResourceManager.GetString("imageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total amount or price of content is not actual.
        /// </summary>
        internal static string InvaliContentCartValueOfPrice {
            get {
                return ResourceManager.GetString("InvaliContentCartValueOfPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid operation add object Defrayal.
        /// </summary>
        internal static string InvalidAddOperationDefrayal {
            get {
                return ResourceManager.GetString("InvalidAddOperationDefrayal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid content identificator.
        /// </summary>
        internal static string InvalidContentId {
            get {
                return ResourceManager.GetString("InvalidContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid operation delete object Defrayal.
        /// </summary>
        internal static string InvalidDeleteOperationDefrayal {
            get {
                return ResourceManager.GetString("InvalidDeleteOperationDefrayal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect id value.
        /// </summary>
        internal static string InvalidIdValue {
            get {
                return ResourceManager.GetString("InvalidIdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase transaction is not successfully.
        /// </summary>
        internal static string InvalidTransactionBuyContent {
            get {
                return ResourceManager.GetString("InvalidTransactionBuyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reward seller transaction is not successfully.
        /// </summary>
        internal static string InvalidTransactionRewardSeller {
            get {
                return ResourceManager.GetString("InvalidTransactionRewardSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write down persentage for store is not successfully.
        /// </summary>
        internal static string InvalidTransactionWriteDownPersentageStore {
            get {
                return ResourceManager.GetString("InvalidTransactionWriteDownPersentageStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value can not be less than or equal zerro.
        /// </summary>
        internal static string LessThanOrEqualToZeroValue {
            get {
                return ResourceManager.GetString("LessThanOrEqualToZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 256.
        /// </summary>
        internal static string MAX_CONTENT {
            get {
                return ResourceManager.GetString("MAX_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 300.
        /// </summary>
        internal static string MaxHeightCompressedImage {
            get {
                return ResourceManager.GetString("MaxHeightCompressedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 300.
        /// </summary>
        internal static string MaxWidthCompressedImage {
            get {
                return ResourceManager.GetString("MaxWidthCompressedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на noreply.mediashop@gmail.com.
        /// </summary>
        internal static string MediaShopMailAddress {
            get {
                return ResourceManager.GetString("MediaShopMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ayTYh?2-3xtUB26j.
        /// </summary>
        internal static string MediaShopMailPassword {
            get {
                return ResourceManager.GetString("MediaShopMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;audio/basic&quot;,
        ///                &quot;audio/L24&quot;,
        ///                &quot;audio/mp4&quot;,
        ///                &quot;audio/aac&quot;,
        ///                &quot;audio/mpeg&quot;,
        ///                &quot;audio/ogg&quot;,
        ///                &quot;audio/vorbis&quot;,
        ///                &quot;audio/x - ms - wma&quot;,
        ///                &quot;audio/x - ms - wax&quot;,
        ///                &quot;audio/vnd.rn - realaudio&quot;,
        ///                &quot;audio/vnd.wave&quot;,
        ///                &quot;audio/webm&quot;.
        /// </summary>
        internal static string musicType {
            get {
                return ResourceManager.GetString("musicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation payment was Created but not Approved.
        /// </summary>
        internal static string NotApprovedOperationPayment {
            get {
                return ResourceManager.GetString("NotApprovedOperationPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content is not exist in Cart.
        /// </summary>
        internal static string NotExistContentInCart {
            get {
                return ResourceManager.GetString("NotExistContentInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product not found with this ID..
        /// </summary>
        internal static string NotFoundProduct {
            get {
                return ResourceManager.GetString("NotFoundProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User has not been subscribed to receive notification.
        /// </summary>
        internal static string NotSubscribedUserMessage {
            get {
                return ResourceManager.GetString("NotSubscribedUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object type Defrayal is null .
        /// </summary>
        internal static string NullModelDefrayal {
            get {
                return ResourceManager.GetString("NullModelDefrayal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content can not be null.
        /// </summary>
        internal static string NullOrEmptyContent {
            get {
                return ResourceManager.GetString("NullOrEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value can not be null.
        /// </summary>
        internal static string NullOrEmptyValue {
            get {
                return ResourceManager.GetString("NullOrEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на String can not be null or empty.
        /// </summary>
        internal static string NullOrEmptyValueString {
            get {
                return ResourceManager.GetString("NullOrEmptyValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment not found.
        /// </summary>
        internal static string PaymentIsNullOrEmpty {
            get {
                return ResourceManager.GetString("PaymentIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It&apos;s registration message from Media shop. Follow the link to continue: {0}.
        /// </summary>
        internal static string RegisterUserMailBody {
            get {
                return ResourceManager.GetString("RegisterUserMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Satate of Content is not valid.
        /// </summary>
        internal static string StateContentError {
            get {
                return ResourceManager.GetString("StateContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Template file {0} not found.
        /// </summary>
        internal static string TemplateFileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("TemplateFileNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product has unknow type.
        /// </summary>
        internal static string UnknowProductType {
            get {
                return ResourceManager.GetString("UnknowProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unspecified path in {0} to the message template {1}..
        /// </summary>
        internal static string UnspecifiedPathToTheMessageTemplate {
            get {
                return ResourceManager.GetString("UnspecifiedPathToTheMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content is not update in cart.
        /// </summary>
        internal static string UpdateContentInCart {
            get {
                return ResourceManager.GetString("UpdateContentInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update  product error.
        /// </summary>
        internal static string UpdateProductError {
            get {
                return ResourceManager.GetString("UpdateProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload product error.
        /// </summary>
        internal static string UploadProductError {
            get {
                return ResourceManager.GetString("UploadProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;video/mpeg&quot;,
        ///                &quot;video/mp4&quot;,
        ///                &quot;video/ogg&quot;,
        ///                &quot;video/quicktime&quot;,
        ///                &quot;video/webm&quot;,
        ///                &quot;video/x - ms - wmv&quot;,
        ///                &quot;video/x - flv&quot;,
        ///                &quot;video/3gpp&quot;,
        ///                &quot;video/3gpp2&quot;.
        /// </summary>
        internal static string videoType {
            get {
                return ResourceManager.GetString("videoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WaterMark {
            get {
                object obj = ResourceManager.GetObject("WaterMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.5.
        /// </summary>
        internal static string WatermarkOpacity {
            get {
                return ResourceManager.GetString("WatermarkOpacity", resourceCulture);
            }
        }
    }
}
